version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: learn_fastapi
      POSTGRES_USER: hero
      POSTGRES_PASSWORD: 123456
    ports: ["5432:5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hero -d learn_fastapi"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports: ["6379:6379"]

  
volumes:
  pgdata:
