"""create users table

Revision ID: c237a7cc5fcd
Revises: 
Create Date: 2025-10-07 11:47:43.909300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c237a7cc5fcd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###

    # 插入默认用户
    default_email = "admin@admin.com"
    # 这里的密码是 'admin' 的 bcrypt hash，可根据实际需要替换
    default_hashed_password = "$2b$12$KIXQ4b1r5QyQeFQxQ1QeF.QQeFQxQ1QeFQxQ1QeFQxQ1QeFQxQ1QeF"
    conn = op.get_bind()
    conn.execute(
        sa.text(
            "INSERT INTO users (email, hashed_password, is_active) VALUES (:email, :hashed_password, :is_active)"
        ),
        {"email": default_email, "hashed_password": default_hashed_password, "is_active": True}
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
